/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessgame;

import id.co.indocyber.guessgame.model.WordModel;
import id.co.indocyber.guessgame.model.WordQuestionGenerator;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
    WordModel modelWord;
    //String[] bankSoal= {"Pondok Indah","Sudirman","Tugu Tani","Citos","Gandariya City"};
    
    //seolah olah database
//    WordModel soal1=new WordModel("Pondok Indah","Daerah di Jakarta Selatan");
//    WordModel soal2=new WordModel("Sudirman","Jalan Utama di Jakarta");
//    WordModel soal3=new WordModel("Tugu Tani","Patung Dekat Monas");
//    WordModel soal4=new WordModel("Citos","Mall di Jakarta Selatan");
//    WordModel soal5=new WordModel("Gandariya City","Mall Anak Muda di Jakarta Selatan");
//    
//    WordModel[] bankSoal={soal1,soal2,soal3,soal4,soal5};
    
    List<WordModel> bankSoal;
    
    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        
        
        bankSoal= WordQuestionGenerator.createQuestGeneratorCollection();
        initComponents();
        setTitle("Tebak Tebakan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        periksaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        commentJawabanLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        hintButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();
        hintTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalTextField.setEditable(false);

        periksaButton.setText("Periksa");
        periksaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periksaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban:");

        jLabel2.setText("Soal");

        commentJawabanLabel.setText("Belum Ada Jawaban");

        startButton.setText("Mulai");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kota", "buah-buahan", "mall", "hewan" }));

        hintButton.setText("Bantuan");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("Hint:");

        hintTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hintButton)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(hintLabel)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(commentJawabanLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(periksaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(hintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintButton)
                    .addComponent(startButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintLabel)
                    .addComponent(hintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(periksaButton)
                .addGap(11, 11, 11)
                .addComponent(commentJawabanLabel)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
         //untuk memunculkan bankSoal
       int soalIndex=(int) Math.floor(Math.random()* bankSoal.size());//floor digunakan untuk mengubah nilai menjadi positif

        modelWord=bankSoal.get(soalIndex);//bankSoal[soalIndex];
        soalTextField.setText(modelWord.acakHuruf());
        
        jawabanTextField.setText("");
        hintTextField.setText("");
        //
//        modelWord=modelWord.toUpperCase();
//        String[] arrayOfWord= modelWord.split("");       
//        //jika ingin mengambil anggota adalah dengan mengambil nama variabelnya
//        //dengan indeks dimulai dari 0        
////        System.out.println("huruf ke3 :" +arrayOfWord[2]);
////        
//        for(int i= 0; i<arrayOfWord.length; i++){
//            System.out.println(arrayOfWord[i]);
//    }
//        //dengan menggunakan sort yang mengambil object berupa String dengan mengambil dari huruf besar
//        //setelah itu huruf kecil yang berurutan dari a-z
//        Arrays.sort(arrayOfWord);
//        StringBuilder sb=new StringBuilder();
//        System.out.println("\n setelah disort\n");
//         for(int i= 0; i<arrayOfWord.length; i++){                                        
//            sb.append(arrayOfWord[i]);
//        
//         }
//         
//         String soal=sb.toString();
//         System.out.println("Soal yang harus dijawab :"+soal.trim());
//         soalTextField.setText(soal.trim());
        
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void periksaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periksaButtonActionPerformed
        // TODO add your handling code here:
        String jawaban=jawabanTextField.getText().trim();
        modelWord.setJawaban(jawaban);
        if(modelWord.cekJawaban()){
            commentJawabanLabel.setText("Jeniuss!!");
        }else{
            commentJawabanLabel.setText("Coba Lagi");
        }
        
    }//GEN-LAST:event_periksaButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
        hintTextField.setText(modelWord.getHint());
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentJawabanLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JTextField hintTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JButton periksaButton;
    private javax.swing.JTextField soalTextField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
